<?php include 'navbar.php' ;?>
    <!-- Breadcrumb -->
    <div class="breadcrumb-bar">
        <a href="#">Home</a> /
        <a href="#">Panthenol Hydrating Gel Sunscreen SPF 60 PA++++</a>
    </div>

    <!-- Main product layout -->
    <div class="container">
        <div class="product-wrapper">

            <!-- ═══ LEFT: Sticky image section ═══ -->
            <div class="product_img_section" id="imgSection">

                <!-- Thumbnail column -->
                <div class="thumb-col" id="thumbCol">
                    <!-- Thumbs generated by JS -->
                </div>

                <!-- Main image + arrow zones -->
                <div class="main-img-wrap" id="mainImgWrap">
                    <div class="arrow-zone left" id="arrowLeft">
                        <div class="arrow-btn"><i class="fa fa-chevron-left"></i></div>
                    </div>

                    <img class="main-img" id="mainImg" src="" alt="Product" />

                    <div class="arrow-zone right" id="arrowRight">
                        <div class="arrow-btn"><i class="fa fa-chevron-right"></i></div>
                    </div>
                </div>
            </div>

            <!-- ═══ RIGHT: Scrollable product content ═══ -->
            <div class="right_side_product">

                <!-- Stamp badge -->
                <div class="badge-stamp">BEST<br>SELLER<br>★</div>

                <!-- Title & rating -->
                <div class="product-brand">/PHD</div>
                <div class="product-title">Panthenol</div>
                <div class="product-subtitle">Hydrating Gel Sunscreen</div>

                <div class="star-row">
                    <span class="stars">★★★★<span style="color:#ccc">★</span></span>
                    <span class="review-count">4.1 | 312 reviews</span>
                </div>

                <div class="spf-badge">SPF 60 PA++++</div>

                <div class="product-desc">
                    Photostable, lightweight sunscreen with New-Gen filters for broad-spectrum UVA,
                    UVB &amp; blue-light protection.
                </div>

                <div class="size-tag">50 ml / 1.69 fl. oz.</div>

                <div class="price-row">
                    <span class="price-mrp-label">MRP:</span>
                    <span class="price-main">₹599</span>
                </div>

                <div class="must-pick-note">
                    <i class="fa fa-check-circle"></i>
                    Must pick (4 products – Best value) &nbsp;
                    <span style="color:#b01b2e;font-weight:700;">Discount 32%</span>
                </div>

                <button class="btn-buy">BUY NOW</button>
                <div class="bought-note">🛒 #1 Bought in past month</div>

                <hr class="sec-divider" />

                <!-- ─── BENEFITS ─── -->
                <div class="sec-title">BENEFITS</div>

                <div class="benefit-item">
                    <div class="benefit-icon"><i class="fa fa-shield-halved"></i></div>
                    <div class="benefit-text">European Standard New-Gen Filters</div>
                    <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
                </div>
                <div class="benefit-item">
                    <div class="benefit-icon"><i class="fa fa-sun"></i></div>
                    <div class="benefit-text">Comfortable for Everyday Use</div>
                    <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
                </div>
                <div class="benefit-item">
                    <div class="benefit-icon"><i class="fa fa-flask"></i></div>
                    <div class="benefit-text">In Vivo and In Vitro Tested</div>
                    <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
                </div>

                <hr class="sec-divider" />

                <!-- ─── THE EXPERIENCE ─── -->
                <div class="sec-title">THE EXPERIENCE</div>
                <div class="experience-grid">
                    <div>
                        <div class="exp-card" style="background:linear-gradient(160deg,#3a2a1a,#6b4226)">
                            <div class="exp-overlay">
                                <div class="exp-for">FOR</div>
                                <div class="exp-label" style="font-size:12px">All Skin Types</div>
                            </div>
                        </div>
                        <div class="exp-caption">All Skin Types</div>
                    </div>
                    <div>
                        <div class="exp-card" style="background:linear-gradient(160deg,#6b1a1a,#9b2e2e)">
                            <div class="exp-overlay">
                                <div class="exp-for">SMELL</div>
                                <div class="exp-label" style="font-size:10px">Fragrance-<br>Free</div>
                            </div>
                        </div>
                        <div class="exp-caption">Fragrance-Free</div>
                    </div>
                    <div>
                        <div class="exp-card" style="background:linear-gradient(160deg,#c8a480,#e8c9a0)">
                            <div class="exp-overlay">
                                <div class="exp-for" style="color:rgba(0,0,0,0.5)">FEEL</div>
                                <div class="exp-label" style="color:#fff;font-size:10px">Quick-<br>Absorbing</div>
                            </div>
                        </div>
                        <div class="exp-caption">Quick-Absorbing, Lightweight, Non-Stinging Sunscreen Gel</div>
                    </div>
                </div>

                <hr class="sec-divider" />

                <!-- ─── WHAT THE DERMAT SAYS ─── -->
                <div class="dermat-box">
                    <div class="dermat-title">WHAT THE DERMAT SAYS</div>
                    <div class="dermat-quote">
                        UV-induced damage drives skin aging and increases the risk of skin cancer, so daily SPF is essential.
                        However, many sunscreens can feel greasy and heavy. PHD's new panthenol hydrating gel sunscreen is
                        not only certified to provide high levels of UVA and UVB protection, but also has a super lightweight
                        texture. This makes it an ideal choice for daily sun protection without heaviness or leaving a white cast.
                    </div>
                    <div class="dermat-avatar-placeholder">
                        <i class="fa fa-user-doctor"></i>
                    </div>
                    <div class="dermat-name">Dr. Max Emmerich</div>
                    <div class="dermat-cred">Dermatologist, United Kingdom<br>MA (Cantab.) BM BCh MRCP (UK)</div>
                </div>

                <hr class="sec-divider" />

                <!-- ─── ACTIVE INGREDIENTS ─── -->
                <div class="sec-title">ACTIVE INGREDIENTS</div>
                <div class="ingredients-grid">
                    <div class="ing-card">
                        <div class="ing-bg ing-bg-1"></div>
                        <div class="ing-content">
                            <div>
                                <div class="ing-name">New-Gen UV Filters</div>
                                <div class="ing-desc">High-Performance Broad-Spectrum Protection</div>
                            </div>
                            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
                        </div>
                    </div>
                    <div class="ing-card">
                        <div class="ing-bg ing-bg-2"></div>
                        <div class="ing-content">
                            <div>
                                <div class="ing-name">Panthenol &amp; Aquaxyl™</div>
                                <div class="ing-desc">Hydration, Calm &amp; Barrier Support</div>
                            </div>
                            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
                        </div>
                    </div>
                    <div class="ing-card">
                        <div class="ing-bg ing-bg-3"></div>
                        <div class="ing-content">
                            <div>
                                <div class="ing-name">Zinc Oxide</div>
                                <div class="ing-desc">Mineral UV Protection &amp; Skin Comfort</div>
                            </div>
                            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
                        </div>
                    </div>
                    <div class="ing-card">
                        <div class="ing-bg ing-bg-4"></div>
                        <div class="ing-content">
                            <div>
                                <div class="ing-name">Thermus Thermophilus Ferment</div>
                                <div class="ing-desc">Infrared Protection</div>
                            </div>
                            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="view-ingredients-link"><a href="#">View Full Ingredients list</a></div>

                <hr class="sec-divider" />

                <!-- ─── PRODUCT INFORMATION ─── -->
                <div class="sec-title">PRODUCT INFORMATION</div>
                <div class="info-tabs">
                    <div class="info-tab active" onclick="switchTab(this,'desc')">Description</div>
                    <div class="info-tab" onclick="switchTab(this,'how')">How to Use</div>
                    <div class="info-tab" onclick="switchTab(this,'other')">Other Details</div>
                </div>

                <div id="tab-desc">
                    <div class="product-desc-text">
                        Powered with high-efficacy SPF 60 PA++++, this broad-spectrum sunscreen protects against UVA &amp;
                        UVB rays to help prevent tanning, sun damage, and premature ageing. Crafted with new-generation,
                        photostable UV filters for long-lasting protection…
                    </div>
                    <span class="read-more-link"
                        onclick="this.parentElement.querySelector('.product-desc-text').style.webkitLineClamp='unset'">
                        Read more ›
                    </span>
                </div>
                <div id="tab-how" style="display:none">
                    <div class="product-desc-text">
                        Apply a generous amount (about 1/4 teaspoon) to face and neck 15–20 minutes before sun exposure.
                        Reapply every 2 hours or after swimming/sweating. For best results, use as the last step of your
                        morning skincare routine before makeup.
                    </div>
                </div>
                <div id="tab-other" style="display:none">
                    <div class="product-desc-text">
                        <strong>Size:</strong> 50ml / 1.69 fl. oz.<br>
                        <strong>Skin Type:</strong> All skin types<br>
                        <strong>Fragrance:</strong> Fragrance-Free<br>
                        <strong>Country of Origin:</strong> Germany<br>
                        <strong>Shelf Life:</strong> 36 months from manufacture date
                    </div>
                </div>

                <!-- Consumer Study -->
                <div class="consumer-study">
                    <div class="consumer-study-title">CONSUMER STUDY</div>
                    <div class="study-stats">
                        <div class="stat-item">
                            <div class="stat-circle">99%</div>
                            <div class="stat-label">Felt protected from sun exposure</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-circle">100%</div>
                            <div class="stat-label">Found it lightweight, non-greasy &amp; comfortable</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-circle">100%</div>
                            <div class="stat-label">Said it absorbed quickly with no white cast</div>
                        </div>
                    </div>
                    <div class="study-footnote">Based on 4-week consumer usage</div>
                </div>

                <hr class="sec-divider" />

                <!-- ─── ROUTINE ─── -->
                <div class="sec-title">COMPLETE THE ROUTINE</div>
                <div class="routine-grid">

                    <!-- Dr. Max Emmerich -->
                    <div class="routine-card">
                        <div class="routine-card-header">
                            <div class="routine-doctor">DR. MAX EMMERICH RECOMMENDS</div>
                            SOLUTION FOR POST-ACNE MARKS AND BLEMISHES
                        </div>
                        <div class="routine-body">
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 1 · CLEANSER</div>
                                    <div class="step-name">Ceramide Hyd…</div>
                                </div>
                                <div class="step-price">₹315</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 2 · SERUM</div>
                                    <div class="step-name">10% Niacina…</div>
                                </div>
                                <div class="step-price">₹649</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 3 · MOISTURIZER</div>
                                    <div class="step-name">3% Niacinam…</div>
                                </div>
                                <div class="step-price">₹549</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 4 · SUNSCREEN</div>
                                    <div class="step-name">Panth…</div>
                                </div>
                                <div class="step-price">₹599</div>
                                <button class="step-this-btn">THIS PRODUCT</button>
                            </div>
                        </div>
                        <div class="routine-footer">
                            <div class="routine-total">
                                <span>4 items selected</span>
                                <span class="routine-old-price">₹2,112</span>
                                <span class="routine-new-price">₹1,436</span>
                                <span class="routine-save">32% OFF</span>
                            </div>
                            <div style="font-size:10px;color:#27ae60;margin-bottom:8px;font-family:Arial">You save ₹675</div>
                            <button class="routine-cta">ADD COMPLETE ROUTINE</button>
                            <div class="routine-individual">or add products individually</div>
                        </div>
                    </div>

                    <!-- Dr. Trisha Khanna -->
                    <div class="routine-card">
                        <div class="routine-card-header">
                            <div class="routine-doctor">DR. TRISHA KHANNA RECOMMENDS</div>
                            SOLUTION FOR HYPERPIGMENTATION, ACNE MARKS AND AGE SPOTS
                        </div>
                        <div class="routine-body">
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 1 · CLEANSER</div>
                                    <div class="step-name">Ceramide Hyd…</div>
                                </div>
                                <div class="step-price">₹315</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 2 · SERUM</div>
                                    <div class="step-name">2% Alpha Arb…</div>
                                </div>
                                <div class="step-price">₹699</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 3 · MOISTURIZER</div>
                                    <div class="step-name">3% Niacinam…</div>
                                </div>
                                <div class="step-price">₹549</div>
                                <button class="step-add-btn">ADD</button>
                            </div>
                            <div class="routine-step">
                                <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
                                <div style="flex:1">
                                    <div class="step-label">STEP 4 · SUNSCREEN</div>
                                    <div class="step-name">Panth…</div>
                                </div>
                                <div class="step-price">₹599</div>
                                <button class="step-this-btn">THIS PRODUCT</button>
                            </div>
                        </div>
                        <div class="routine-footer">
                            <div class="routine-total">
                                <span>4 items selected</span>
                                <span class="routine-old-price">₹2,162</span>
                                <span class="routine-new-price">₹1,470</span>
                                <span class="routine-save">32% OFF</span>
                            </div>
                            <div style="font-size:10px;color:#27ae60;margin-bottom:8px;font-family:Arial">You save ₹691</div>
                            <button class="routine-cta">ADD COMPLETE ROUTINE</button>
                            <div class="routine-individual">or add products individually</div>
                        </div>
                    </div>

                </div><!-- /routine-grid -->

            </div><!-- /right_side_product -->
        </div>
    </div>
    <!-- /product-wrapper -->


    <section>
        <div class="container">
            <div class="product_got_question mt-5 pt-4 border-top">
                <div class="row">
                    <div class="col-md-4">
                        <h4 class="fw-bold">GOT QUESTIONS?</h4>
                    </div>

                    <div class="col-md-8">
                        <div class="accordion accordion-flush" id="faqAccordion">

                            <div class="accordion-item border-bottom">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#faq1">
                                        Is this sunscreen In-Vivo Tested?
                                    </button>
                                </h2>
                                <div id="faq1" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                                    <div class="accordion-body px-0 text-muted small">
                                        Yes! This product has been both in-vivo and in-vitro tested to ensure its efficacy and safety.
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item border-bottom">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#faq2">
                                        Is it safe for daily use?
                                    </button>
                                </h2>
                                <div id="faq2" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                                    <div class="accordion-body px-0 text-muted small">
                                        Yes. It’s designed for everyday protection against UVA, UVB, and infrared rays. You can use it daily
                                        - whether indoors, commuting, or outdoors.
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item border-bottom">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#faq3">
                                        Can I wear makeup over this sunscreen?
                                    </button>
                                </h2>
                                <div id="faq3" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                                    <div class="accordion-body px-0 text-muted small">
                                        Yes. Its lightweight, non-greasy finish makes it a perfect base under makeup without pilling or
                                        patchiness.
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item border-bottom">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#faq4">
                                        Does this leave white cast?
                                    </button>
                                </h2>
                                <div id="faq4" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                                    <div class="accordion-body px-0 text-muted small">
                                        No, this sunscreen is formulated to leave zero white cast.
                                        Because it’s a lightweight cream sunscreen designed with dermatologists from the USA, UK, and India,
                                        the filters used are chosen to blend seamlessly into Indian skin tones (where white cast is usually
                                        a big concern). That means:

                                        <strong> It absorbs quickly into skin</strong>

                                        Doesn’t leave residue or streaks

                                        <strong> Works well under makeup or on its own</strong>

                                        So it gives you matte protection without the chalky finish many SPF 50 sunscreens cause.
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-item border-bottom">
                                <h2 class="accordion-header">
                                    <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#faq5">
                                        Why is UV-A tested via in-vitro method?
                                    </button>
                                </h2>
                                <div id="faq5" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                                    <div class="accordion-body px-0 text-muted small">
                                        In India, UVA testing is usually done in-vitro to ensure safety and ethics. Testing on human skin
                                        could pose long-term damage risks, so lab-based methods are used to accurately measure UVA
                                        protection without exposing people to harm.
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- <script>
    // ─── Image data (using placeholder SVGs that mimic each section) ───
    const images = [
      {
        label: "Main",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 320">
        <rect width="220" height="320" fill="#f8f4f0"/>
        <rect x="70" y="20" width="80" height="240" rx="8" fill="#b01b2e"/>
        <text x="110" y="130" font-family="Arial" font-size="18" font-weight="bold" fill="white" text-anchor="middle">/PHD</text>
        <text x="110" y="152" font-family="Arial" font-size="9" fill="white" text-anchor="middle">Panthenol</text>
        <text x="110" y="165" font-family="Arial" font-size="9" fill="white" text-anchor="middle">Hydrating Sunscreen</text>
        <rect x="88" y="200" width="44" height="44" rx="22" fill="rgba(255,255,255,0.2)"/>
        <text x="110" y="228" font-family="Arial" font-size="14" font-weight="bold" fill="white" text-anchor="middle">6C</text>
        <rect x="75" y="255" width="70" height="6" rx="3" fill="#888"/>
      </svg>`
      },
      {
        label: "Angle",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 320">
        <rect width="220" height="320" fill="#f0ede9"/>
        <rect x="60" y="30" width="75" height="230" rx="8" fill="#9a1626" transform="rotate(-6,97,145)"/>
        <text x="105" y="145" font-family="Arial" font-size="14" font-weight="bold" fill="white" text-anchor="middle" transform="rotate(-6,105,145)">/PHD</text>
        <text x="105" y="175" font-family="Arial" font-size="9" fill="white" text-anchor="middle" transform="rotate(-6,105,175)">SPF 60</text>
      </svg>`
      },
      {
        label: "Skin",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 220">
        <rect width="220" height="220" fill="#d4a882"/>
        <ellipse cx="110" cy="110" rx="90" ry="90" fill="#c49060"/>
        <text x="110" y="100" font-family="Arial" font-size="11" fill="white" text-anchor="middle">FOR</text>
        <text x="110" y="125" font-family="Arial" font-size="18" font-weight="bold" fill="white" text-anchor="middle">ALL SKIN</text>
        <text x="110" y="145" font-family="Arial" font-size="18" font-weight="bold" fill="white" text-anchor="middle">TYPES</text>
      </svg>`
      },
      {
        label: "Bottle",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 220">
        <rect width="220" height="220" fill="#8a1522"/>
        <rect x="80" y="30" width="60" height="160" rx="6" fill="#b01b2e"/>
        <rect x="80" y="30" width="60" height="20" rx="3" fill="#333"/>
        <text x="110" y="120" font-family="Arial" font-size="10" fill="white" text-anchor="middle">FRAGRANCE</text>
        <text x="110" y="135" font-family="Arial" font-size="10" fill="white" text-anchor="middle">FREE</text>
      </svg>`
      },
      {
        label: "Texture",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 220">
        <rect width="220" height="220" fill="#e8d5bb"/>
        <circle cx="110" cy="110" r="70" fill="rgba(200,169,110,0.4)"/>
        <text x="110" y="95" font-family="Arial" font-size="10" fill="#333" text-anchor="middle">LIGHTWEIGHT</text>
        <text x="110" y="115" font-family="Arial" font-size="10" fill="#333" text-anchor="middle">GEL TEXTURE</text>
        <text x="110" y="135" font-family="Arial" font-size="10" fill="#333" text-anchor="middle">NO WHITE CAST</text>
      </svg>`
      },
      {
        label: "Badge",
        svg: `<svg xmlns="./assets/img/sample1.png" viewBox="0 0 220 220">
        <rect width="220" height="220" fill="#f8f4f0"/>
        <circle cx="110" cy="110" r="80" fill="none" stroke="#b01b2e" stroke-width="3"/>
        <text x="110" y="90" font-family="Arial" font-size="12" font-weight="bold" fill="#b01b2e" text-anchor="middle">NEW GEN</text>
        <text x="110" y="110" font-family="Arial" font-size="10" fill="#333" text-anchor="middle">UV FILTERS</text>
        <text x="110" y="130" font-family="Arial" font-size="9" fill="#666" text-anchor="middle">European Standard</text>
      </svg>`
      }
    ];

    let currentIndex = 0;

    // Convert SVG string to data URL
    function svgToDataUrl(svgStr) {
      return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svgStr);
    }

    // Build thumbnails
    const thumbCol = document.getElementById('thumbCol');
    images.forEach((img, i) => {
      const div = document.createElement('div');
      div.className = 'thumb-item' + (i === 0 ? ' active' : '');
      div.innerHTML = `<img src="${svgToDataUrl(img.svg)}" alt="${img.label}"/>`;
      div.addEventListener('click', () => setImage(i));
      thumbCol.appendChild(div);
    });

    const mainImg = document.getElementById('mainImg');

    function setImage(index) {
      currentIndex = (index + images.length) % images.length;
      mainImg.style.opacity = '0';
      setTimeout(() => {
        mainImg.src = svgToDataUrl(images[currentIndex].svg);
        mainImg.alt = images[currentIndex].label;
        mainImg.style.opacity = '1';
      }, 150);
      // Update thumb highlights
      document.querySelectorAll('.thumb-item').forEach((t, i) => {
        t.classList.toggle('active', i === currentIndex);
      });
    }

    // Init first image
    setImage(0);

    // Arrow controls
    document.getElementById('arrowLeft').addEventListener('click', () => setImage(currentIndex - 1));
    document.getElementById('arrowRight').addEventListener('click', () => setImage(currentIndex + 1));

    // Tab switching
    function switchTab(el, id) {
      document.querySelectorAll('.info-tab').forEach(t => t.classList.remove('active'));
      el.classList.add('active');
      ['desc', 'how', 'other'].forEach(tid => {
        document.getElementById('tab-' + tid).style.display = tid === id ? '' : 'none';
      });
    }
  </script> -->


    <script>
        // 1. Array lo direct ga mee local image paths ivvandi
        const images = [{
                label: "Main",
                src: "./assets/img/sample1.png"
            },
            {
                label: "Angle",
                src: "./assets/img/sample1.png"
            },
            {
                label: "Skin",
                src: "./assets/img/sample1.png"
            },
            {
                label: "Bottle",
                src: "./assets/img/sample1.png"
            },
            {
                label: "Texture",
                src: "./assets/img/sample1.png"
            },
            {
                label: "Badge",
                src: "./assets/img/sample1.png"
            }
        ];

        let currentIndex = 0;
        const mainImg = document.getElementById('mainImg');
        const thumbCol = document.getElementById('thumbCol');

        // 2. Thumbnails generate cheyadam
        images.forEach((img, i) => {
            const div = document.createElement('div');
            div.className = 'thumb-item' + (i === 0 ? ' active' : '');
            // Ikkada direct ga img.src vadutunnam
            div.innerHTML = `<img src="${img.src}" alt="${img.label}" style="width:100%; height:auto;"/>`;
            div.addEventListener('click', () => setImage(i));
            thumbCol.appendChild(div);
        });

        // 3. Image change function
        function setImage(index) {
            // Index round robin (last nundi first ki, first nundi last ki)
            currentIndex = (index + images.length) % images.length;

            // Smooth transition kosam opacity toggle
            mainImg.style.opacity = '0';

            setTimeout(() => {
                mainImg.src = images[currentIndex].src; // Local path set avtundi
                mainImg.alt = images[currentIndex].label;
                mainImg.style.opacity = '1';
            }, 150);

            // Active thumbnail highlight update
            document.querySelectorAll('.thumb-item').forEach((t, i) => {
                t.classList.toggle('active', i === currentIndex);
            });
        }

        // Modal initial load
        setImage(0);

        // Arrow controls
        document.getElementById('arrowLeft').addEventListener('click', () => setImage(currentIndex - 1));
        document.getElementById('arrowRight').addEventListener('click', () => setImage(currentIndex + 1));
    </script>
    <?php include 'footer.php'; ?>
</body>

</html>