<?php include 'navbar.php'; ?>

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
  <a href="#">Home</a> /
  <a id="breadcrumbProduct" href="#">10% Niacinamide Spot Correcting Serum</a>
</div>

<!-- Main product layout -->
<div class="container">
  <div class="product-wrapper">

    <!-- ═══ LEFT: Sticky image section ═══ -->
    <div class="product_img_section" id="imgSection">

      <!-- Thumbnail column -->
      <div class="thumb-col" id="thumbCol">
        <!-- Thumbs generated by JS -->
      </div>

      <!-- Main image + arrow zones -->
      <div class="main-img-wrap" id="mainImgWrap">
        <div class="arrow-zone left" id="arrowLeft">
          <div class="arrow-btn"><i class="fa fa-chevron-left"></i></div>
        </div>

        <img class="main-img" id="mainImg" src="" alt="Product" />

        <div class="arrow-zone right" id="arrowRight">
          <div class="arrow-btn"><i class="fa fa-chevron-right"></i></div>
        </div>
      </div>
    </div>

    <!-- ═══ RIGHT: Scrollable product content ═══ -->
    <div class="right_side_product">

      <!-- Stamp badge -->
      <div class="badge-stamp">BEST<br>SELLER<br>★</div>

      <!-- Title & rating -->
      <div class="product-brand">/PHD</div>
      <div class="product-title" id="productTitle">10% Niacinamide Spot Correcting Serum</div>
      <div class="product-subtitle" id="productSubtitle">/Solution for post-acne marks and blemishes/</div>

      <div class="star-row">
        <span class="stars" id="productStars">★★★★<span style="color:#ccc">★</span></span>
        <span class="review-count" id="productReviews">4.1 | 312 reviews</span>
      </div>

      <div class="spf-badge" id="spfBadge">SPF 60 PA++++</div>

      <div class="product-desc" id="productDesc">
        Photostable, lightweight sunscreen with New-Gen filters for broad-spectrum UVA,
        UVB &amp; blue-light protection.
      </div>

      <div class="size-tag" id="sizeTag">50 ml / 1.69 fl. oz.</div>

      <div class="price-row">
        <span class="price-mrp-label">MRP:</span>
        <span class="price-main" id="productPrice">₹599</span>
      </div>

      <div class="must-pick-note" id="discountNote" style="display:none">
        <i class="fa fa-check-circle"></i>
        Must pick (4 products – Best value) &nbsp;
        <span style="color:var(--red);font-weight:700;" id="discountPercent">Discount 32%</span>
      </div>

      <button class="btn-buy">BUY NOW</button>
      <div class="bought-note">🛒 #1 Bought in past month</div>

      <hr class="sec-divider" />

      <!-- ─── BENEFITS ─── -->
      <div class="sec-title">BENEFITS</div>

      <div class="benefit-item">
        <div class="benefit-icon"><i class="fa fa-shield-halved"></i></div>
        <div class="benefit-text">European Standard New-Gen Filters</div>
        <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
      </div>
      <div class="benefit-item">
        <div class="benefit-icon"><i class="fa fa-sun"></i></div>
        <div class="benefit-text">Comfortable for Everyday Use</div>
        <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
      </div>
      <div class="benefit-item">
        <div class="benefit-icon"><i class="fa fa-flask"></i></div>
        <div class="benefit-text">In Vivo and In Vitro Tested</div>
        <div class="benefit-chevron"><i class="fa fa-chevron-down"></i></div>
      </div>

      <hr class="sec-divider" />

      <!-- ─── THE EXPERIENCE ─── -->
      <div class="sec-title">THE EXPERIENCE</div>
      <div class="experience-grid">
        <div>
          <div class="exp-card" style="background:linear-gradient(160deg,#3a2a1a,#6b4226)">
            <div class="exp-overlay">
              <div class="exp-for">FOR</div>
              <div class="exp-label" style="font-size:12px">All Skin Types</div>
            </div>
          </div>
          <div class="exp-caption">All Skin Types</div>
        </div>
        <div>
          <div class="exp-card" style="background:linear-gradient(160deg,#6b1a1a,#9b2e2e)">
            <div class="exp-overlay">
              <div class="exp-for">SMELL</div>
              <div class="exp-label" style="font-size:10px">Fragrance-<br>Free</div>
            </div>
          </div>
          <div class="exp-caption">Fragrance-Free</div>
        </div>
        <div>
          <div class="exp-card" style="background:linear-gradient(160deg,#c8a480,#e8c9a0)">
            <div class="exp-overlay">
              <div class="exp-for" style="color:rgba(0,0,0,0.5)">FEEL</div>
              <div class="exp-label" style="color:#fff;font-size:10px">Quick-<br>Absorbing</div>
            </div>
          </div>
          <div class="exp-caption">Quick-Absorbing, Lightweight, Non-Stinging Sunscreen Gel</div>
        </div>
      </div>

      <hr class="sec-divider" />

      <!-- ─── WHAT THE DERMAT SAYS ─── -->
      <div class="dermat-box">
        <div class="dermat-title">WHAT THE DERMAT SAYS</div>
        <div class="dermat-quote">
          UV-induced damage drives skin aging and increases the risk of skin cancer, so daily SPF is essential.
          However, many sunscreens can feel greasy and heavy. PHD's new panthenol hydrating gel sunscreen is
          not only certified to provide high levels of UVA and UVB protection, but also has a super lightweight
          texture. This makes it an ideal choice for daily sun protection without heaviness or leaving a white cast.
        </div>
        <div class="dermat-avatar-placeholder">
          <i class="fa fa-user-doctor"></i>
        </div>
        <div class="dermat-name">Dr. Max Emmerich</div>
        <div class="dermat-cred">Dermatologist, United Kingdom<br>MA (Cantab.) BM BCh MRCP (UK)</div>
      </div>

      <hr class="sec-divider" />

      <!-- ─── ACTIVE INGREDIENTS ─── -->
      <div class="sec-title">ACTIVE INGREDIENTS</div>
      <div class="ingredients-grid">
        <div class="ing-card">
          <div class="ing-bg ing-bg-1"></div>
          <div class="ing-content">
            <div>
              <div class="ing-name">New-Gen UV Filters</div>
              <div class="ing-desc">High-Performance Broad-Spectrum Protection</div>
            </div>
            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
          </div>
        </div>
        <div class="ing-card">
          <div class="ing-bg ing-bg-2"></div>
          <div class="ing-content">
            <div>
              <div class="ing-name">Panthenol &amp; Aquaxyl™</div>
              <div class="ing-desc">Hydration, Calm &amp; Barrier Support</div>
            </div>
            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
          </div>
        </div>
        <div class="ing-card">
          <div class="ing-bg ing-bg-3"></div>
          <div class="ing-content">
            <div>
              <div class="ing-name">Zinc Oxide</div>
              <div class="ing-desc">Mineral UV Protection &amp; Skin Comfort</div>
            </div>
            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
          </div>
        </div>
        <div class="ing-card">
          <div class="ing-bg ing-bg-4"></div>
          <div class="ing-content">
            <div>
              <div class="ing-name">Thermus Thermophilus Ferment</div>
              <div class="ing-desc">Infrared Protection</div>
            </div>
            <div class="ing-arrow"><i class="fa fa-chevron-right"></i></div>
          </div>
        </div>
      </div>
      <div class="view-ingredients-link"><a href="#">View Full Ingredients list</a></div>

      <hr class="sec-divider" />

      <!-- ─── PRODUCT INFORMATION ─── -->
      <div class="sec-title">PRODUCT INFORMATION</div>
      <div class="info-tabs">
        <div class="info-tab active" onclick="switchTab(this,'desc')">Description</div>
        <div class="info-tab" onclick="switchTab(this,'how')">How to Use</div>
        <div class="info-tab" onclick="switchTab(this,'other')">Other Details</div>
      </div>

      <div id="tab-desc">
        <div class="product-desc-text" id="productDescText">
          Powered with high-efficacy SPF 60 PA++++, this broad-spectrum sunscreen protects against UVA &amp;
          UVB rays to help prevent tanning, sun damage, and premature ageing. Crafted with new-generation,
          photostable UV filters for long-lasting protection…
        </div>
        <span class="read-more-link"
          onclick="this.parentElement.querySelector('.product-desc-text').style.webkitLineClamp='unset'">
          Read more ›
        </span>
      </div>
      <div id="tab-how" style="display:none">
        <div class="product-desc-text" id="howToUseText">
          Apply a generous amount (about 1/4 teaspoon) to face and neck 15–20 minutes before sun exposure.
          Reapply every 2 hours or after swimming/sweating. For best results, use as the last step of your
          morning skincare routine before makeup.
        </div>
      </div>
      <div id="tab-other" style="display:none">
        <div class="product-desc-text" id="otherDetailsText">
          <strong>Size:</strong> 50ml / 1.69 fl. oz.<br>
          <strong>Skin Type:</strong> All skin types<br>
          <strong>Fragrance:</strong> Fragrance-Free<br>
          <strong>Country of Origin:</strong> Germany<br>
          <strong>Shelf Life:</strong> 36 months from manufacture date
        </div>
      </div>

      <!-- Consumer Study -->
      <div class="consumer-study">
        <div class="consumer-study-title">CONSUMER STUDY</div>
        <div class="study-stats">
          <div class="stat-item">
            <div class="stat-circle">99%</div>
            <div class="stat-label">Felt protected from sun exposure</div>
          </div>
          <div class="stat-item">
            <div class="stat-circle">100%</div>
            <div class="stat-label">Found it lightweight, non-greasy &amp; comfortable</div>
          </div>
          <div class="stat-item">
            <div class="stat-circle">100%</div>
            <div class="stat-label">Said it absorbed quickly with no white cast</div>
          </div>
        </div>
        <div class="study-footnote">Based on 4-week consumer usage</div>
      </div>

      <hr class="sec-divider" />

      <!-- ─── ROUTINE ─── -->
      <div class="sec-title">COMPLETE THE ROUTINE</div>
      <div class="routine-grid">

        <!-- Dr. Max Emmerich -->
        <div class="routine-card">
          <div class="routine-card-header">
            <div class="routine-doctor">DR. MAX EMMERICH RECOMMENDS</div>
            SOLUTION FOR POST-ACNE MARKS AND BLEMISHES
          </div>
          <div class="routine-body">
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 1 · CLEANSER</div>
                <div class="step-name">Ceramide Hyd…</div>
              </div>
              <div class="step-price">₹315</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 2 · SERUM</div>
                <div class="step-name">10% Niacina…</div>
              </div>
              <div class="step-price">₹649</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 3 · MOISTURIZER</div>
                <div class="step-name">3% Niacinam…</div>
              </div>
              <div class="step-price">₹549</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 4 · SUNSCREEN</div>
                <div class="step-name">Panth…</div>
              </div>
              <div class="step-price">₹599</div>
              <button class="step-this-btn">THIS PRODUCT</button>
            </div>
          </div>
          <div class="routine-footer">
            <div class="routine-total">
              <span>4 items selected</span>
              <span class="routine-old-price">₹2,112</span>
              <span class="routine-new-price">₹1,436</span>
              <span class="routine-save">32% OFF</span>
            </div>
            <div style="font-size:10px;color:#27ae60;margin-bottom:8px;font-family:Arial">You save ₹675</div>
            <button class="routine-cta">ADD COMPLETE ROUTINE</button>
            <div class="routine-individual">or add products individually</div>
          </div>
        </div>

        <!-- Dr. Trisha Khanna -->
        <div class="routine-card">
          <div class="routine-card-header">
            <div class="routine-doctor">DR. TRISHA KHANNA RECOMMENDS</div>
            SOLUTION FOR HYPERPIGMENTATION, ACNE MARKS AND AGE SPOTS
          </div>
          <div class="routine-body">
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 1 · CLEANSER</div>
                <div class="step-name">Ceramide Hyd…</div>
              </div>
              <div class="step-price">₹315</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 2 · SERUM</div>
                <div class="step-name">2% Alpha Arb…</div>
              </div>
              <div class="step-price">₹699</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 3 · MOISTURIZER</div>
                <div class="step-name">3% Niacinam…</div>
              </div>
              <div class="step-price">₹549</div>
              <button class="step-add-btn">ADD</button>
            </div>
            <div class="routine-step">
              <div class="step-check"><i class="fa fa-check" style="font-size:7px"></i></div>
              <div style="flex:1">
                <div class="step-label">STEP 4 · SUNSCREEN</div>
                <div class="step-name">Panth…</div>
              </div>
              <div class="step-price">₹599</div>
              <button class="step-this-btn">THIS PRODUCT</button>
            </div>
          </div>
          <div class="routine-footer">
            <div class="routine-total">
              <span>4 items selected</span>
              <span class="routine-old-price">₹2,162</span>
              <span class="routine-new-price">₹1,470</span>
              <span class="routine-save">32% OFF</span>
            </div>
            <div style="font-size:10px;color:#27ae60;margin-bottom:8px;font-family:Arial">You save ₹691</div>
            <button class="routine-cta">ADD COMPLETE ROUTINE</button>
            <div class="routine-individual">or add products individually</div>
          </div>
        </div>

      </div><!-- /routine-grid -->

    </div><!-- /right_side_product -->
  </div>
</div>
<!-- /product-wrapper -->


<section>
  <div class="container">
    <div class="product_got_question mt-5 pt-4 border-top">
      <div class="row">
        <div class="col-md-4">
          <h4 class="fw-bold">GOT QUESTIONS?</h4>
        </div>

        <div class="col-md-8">
          <div class="accordion accordion-flush" id="faqAccordion">

            <div class="accordion-item border-bottom">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                  data-bs-toggle="collapse" data-bs-target="#faq1">
                  Is this sunscreen In-Vivo Tested?
                </button>
              </h2>
              <div id="faq1" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                <div class="accordion-body px-0 text-muted small">
                  Yes! This product has been both in-vivo and in-vitro tested to ensure its efficacy and safety.
                </div>
              </div>
            </div>

            <div class="accordion-item border-bottom">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                  data-bs-toggle="collapse" data-bs-target="#faq2">
                  Is it safe for daily use?
                </button>
              </h2>
              <div id="faq2" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                <div class="accordion-body px-0 text-muted small">
                  Yes. It’s designed for everyday protection against UVA, UVB, and infrared rays. You can use it daily
                  - whether indoors, commuting, or outdoors.
                </div>
              </div>
            </div>

            <div class="accordion-item border-bottom">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                  data-bs-toggle="collapse" data-bs-target="#faq3">
                  Can I wear makeup over this sunscreen?
                </button>
              </h2>
              <div id="faq3" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                <div class="accordion-body px-0 text-muted small">
                  Yes. Its lightweight, non-greasy finish makes it a perfect base under makeup without pilling or
                  patchiness.
                </div>
              </div>
            </div>

            <div class="accordion-item border-bottom">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                  data-bs-toggle="collapse" data-bs-target="#faq4">
                  Does this leave white cast?
                </button>
              </h2>
              <div id="faq4" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                <div class="accordion-body px-0 text-muted small">
                  No, this sunscreen is formulated to leave zero white cast.
                  Because it’s a lightweight cream sunscreen designed with dermatologists from the USA, UK, and India,
                  the filters used are chosen to blend seamlessly into Indian skin tones (where white cast is usually
                  a big concern). That means:

                  <strong> It absorbs quickly into skin</strong>

                  Doesn’t leave residue or streaks

                  <strong> Works well under makeup or on its own</strong>

                  So it gives you matte protection without the chalky finish many SPF 50 sunscreens cause.
                </div>
              </div>
            </div>

            <div class="accordion-item border-bottom">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed px-0 bg-transparent shadow-none" type="button"
                  data-bs-toggle="collapse" data-bs-target="#faq5">
                  Why is UV-A tested via in-vitro method?
                </button>
              </h2>
              <div id="faq5" class="accordion-collapse collapse" data-bs-parent="#faqAccordion">
                <div class="accordion-body px-0 text-muted small">
                  In India, UVA testing is usually done in-vitro to ensure safety and ethics. Testing on human skin
                  could pose long-term damage risks, so lab-based methods are used to accurately measure UVA
                  protection without exposing people to harm.
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">

  <!-- ════════════════════════════════
       RATINGS & REVIEWS HEADER
  ════════════════════════════════ -->
  <h2 class="section-heading">Ratings &amp; Reviews</h2>

  <!-- Summary row -->
  <div class="rating-summary-card">
    <div class="row g-3 align-items-center">

      <!-- Left: big score -->
      <div class="col-auto text-center" style="min-width:120px">
        <div class="big-score">4.98</div>
        <div class="big-stars">★★★★★</div>
        <div class="review-count-label">Based on 54 reviews</div>
        <div class="verified-badge"><i class="fa fa-circle-check" style="font-size:10px"></i> Verified</div>
      </div>

      <!-- Middle: bar chart -->
      <div class="col">
        <div class="bar-row">
          <div class="bar-label"><span style="color:var(--gold)">★★★★★</span></div>
          <div class="bar-track">
            <div class="bar-fill" style="width:96%"></div>
          </div>
          <div class="bar-count">51</div>
        </div>
        <div class="bar-row">
          <div class="bar-label"><span style="color:var(--gold)">★★★★</span><span style="color:#ddd">★</span></div>
          <div class="bar-track">
            <div class="bar-fill" style="width:4%"></div>
          </div>
          <div class="bar-count">1</div>
        </div>
        <div class="bar-row">
          <div class="bar-label"><span style="color:var(--gold)">★★★</span><span style="color:#ddd">★★</span></div>
          <div class="bar-track">
            <div class="bar-fill" style="width:0%"></div>
          </div>
          <div class="bar-count">0</div>
        </div>
        <div class="bar-row">
          <div class="bar-label"><span style="color:var(--gold)">★★</span><span style="color:#ddd">★★★</span></div>
          <div class="bar-track">
            <div class="bar-fill" style="width:0%"></div>
          </div>
          <div class="bar-count">0</div>
        </div>
        <div class="bar-row">
          <div class="bar-label"><span style="color:var(--gold)">★</span><span style="color:#ddd">★★★★</span></div>
          <div class="bar-track">
            <div class="bar-fill" style="width:0%"></div>
          </div>
          <div class="bar-count">0</div>
        </div>
      </div>

      <!-- Right: buttons -->
      <div class="col-auto" style="min-width:160px">
        <button class="btn-rate" data-bs-toggle="modal" data-bs-target="#rateModal">
          <i class="fa fa-star me-1" style="font-size:12px"></i> Rate Us
        </button>
        <button class="btn-ask" id="openAskForm">
          <i class="fa fa-circle-question me-1" style="font-size:12px"></i> Ask a question
        </button>
      </div>

    </div>
  </div>

  <!-- Customer photos strip -->
  <div class="photos-strip-wrap">
    <div class="photos-strip-title">Customer Photos &amp; Videos</div>
    <div class="photos-strip" id="photoStrip">
      <div class="photo-thumb">🧴</div>
      <div class="photo-thumb">✋</div>
      <div class="photo-thumb">☀️</div>
      <div class="photo-thumb">💧</div>
      <div class="photo-thumb">🪞</div>
      <div class="photo-thumb">📸</div>
      <div class="photo-thumb">🌿</div>
      <div class="photo-see-more">
        <i class="fa fa-images" style="font-size:16px;color:var(--muted)"></i>
        <span>See more</span>
      </div>
    </div>
  </div>

  <!-- Filter bar -->
  <div class="filter-bar">
    <select class="sort-select" id="sortSelect" onchange="sortReviews()">
      <option value="helpful">Most Helpful</option>
      <option value="recent">Most Recent</option>
      <option value="high">Highest Rated</option>
      <option value="low">Lowest Rated</option>
    </select>
    <button class="btn-filter">
      <i class="fa fa-sliders"></i> Filters
    </button>
  </div>

  <!-- ════════════════════════════════
       REVIEW CARDS
  ════════════════════════════════ -->
  <div id="reviewList">

    <!-- Review 1 -->
    <div class="review-card" data-helpful="72" data-rating="5" data-date="2024-03-10">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Vama Sheth</div>
          <div class="reviewer-country">India</div>
          <div class="reviewer-meta">
            <span>Gender: Female</span>
            <span>Age: 18 to 24 years old</span>
            <span>Skin Type: Normal</span>
          </div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★★</div>
          <div class="review-title">Bought it on day of launch!</div>
          <div class="review-body">
            I ordered this as soon as I received a Whatsapp message about the new launch and the product got
            delivered within a day! Pretty much like other products… PHD has nailed this sunscreen. I just did a
            swatch test as soon as I received the product… super super light and hydrating. Cannot wait to use this everyday.
          </div>
          <div class="review-img">🧴</div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">72</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">5</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Review 2 -->
    <div class="review-card" data-helpful="3" data-rating="5" data-date="2024-03-08">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Bala</div>
          <div class="reviewer-country">India</div>
          <div class="reviewer-meta">
            <span>Gender: Male</span>
            <span>Age: 25 to 39 years old</span>
            <span>Skin Type: Oily</span>
          </div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★★</div>
          <div class="review-title">Listen up! 🎧</div>
          <div class="review-body">
            ONE COMMENT: DON'T EVER STOP OR ALTER THIS SUNSCREEN FOR EVER….<br>
            THAT'S IT!<br>
            PHD ROCKS 🚫 NUKES 🟩
          </div>
          <div class="review-img">🌞</div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">3</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">1</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Review 3 -->
    <div class="review-card" data-helpful="2" data-rating="5" data-date="2024-03-05">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Namita</div>
          <div class="reviewer-country">India</div>
          <div class="reviewer-meta">
            <span>Gender: Female</span>
            <span>Age: 18 to 24 years old</span>
          </div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★★</div>
          <div class="review-title">Love the texture</div>
          <div class="review-body">
            This one is so so thin in texture, it literally glides on the skin!… I hated sunscreens because of texture
            but this is good for everyday for me… all new ingredients and panthenol is commendable…
          </div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">2</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">0</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Review 4 -->
    <div class="review-card" data-helpful="1" data-rating="5" data-date="2024-02-28">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Anubhab Nayak</div>
          <div class="reviewer-country">India</div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★★</div>
          <div class="review-title">Good sunscreen</div>
          <div class="review-body">
            The sunscreen texture is very light and doesn't put whitecast on the face considering its SPF60. It also
            works for longer than regular sunscreens at this price range. The gel base keeps the skin hydra…
          </div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">1</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">0</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Review 5 -->
    <div class="review-card" data-helpful="1" data-rating="4" data-date="2024-02-20">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Shruti rai</div>
          <div class="reviewer-country">India</div>
          <div class="reviewer-meta">
            <span>Age: 18 to 24 years old</span>
            <span>Skin Type: Normal</span>
          </div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★<span style="color:#ddd">★</span></div>
          <div class="review-title">Finally after trying 20+ Sunscreen found one 😊😊</div>
          <div class="review-body">
            This one feels like I have not even applied a Sunscreen… no heaviness, no white or greyish cast… it's like
            after applying all the serums you are applying a moisturizer… and the most important part… IT DOESN'T PILL.
            Thank youuuu for bringing a formula even better than the most viral Korean and European Sunscreen at such an affordable price.
          </div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">1</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">0</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Review 6 -->
    <div class="review-card" data-helpful="0" data-rating="5" data-date="2024-02-15">
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">Ekamm Dhilon</div>
          <div class="reviewer-country">India</div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">★★★★★</div>
          <div class="review-title">Terrific purchase</div>
          <div class="review-body">
            This is such a nice sunscreen. It is lightweight and has a matte finish, it does not leave any white cast. Love it.
          </div>
          <div class="review-img">✋</div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">0</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">0</span>
            </button>
          </div>
        </div>
      </div>
    </div>

  </div><!-- /#reviewList -->

  <hr class="hr-soft" />

  <!-- ════════════════════════════════
       Q & A SECTION
  ════════════════════════════════ -->
  <div class="qa-section">
    <div class="d-flex align-items-center justify-content-between flex-wrap gap-2 mb-3">
      <div class="qa-title mb-0">Questions &amp; Answers</div>
      <button class="btn-ask" id="openAskForm2" style="width:auto;padding:9px 20px">
        <i class="fa fa-circle-question me-1" style="font-size:12px"></i> Ask a question
      </button>
    </div>

    <!-- Ask question form (hidden by default) -->
    <div class="ask-form mb-4" id="askFormWrap" style="display:none">
      <label for="qName">Your Name</label>
      <input type="text" id="qName" placeholder="Enter your name" class="mb-3" />

      <label for="qText">Your Question</label>
      <textarea id="qText" rows="3" placeholder="What would you like to know about this product?"></textarea>

      <div class="d-flex align-items-center gap-2 mt-3">
        <button class="btn-submit-q" onclick="submitQuestion()">Submit Question</button>
        <button class="btn-cancel-q" onclick="closeAskForm()">Cancel</button>
      </div>
      <div id="qError" style="color:var(--red);font-size:12px;margin-top:8px;display:none">
        Please fill in both your name and question.
      </div>
    </div>

    <!-- Q&A list -->
    <div id="qaList">
      <!-- Prepopulated question 1 -->
      <div class="question-card">
        <div class="question-header">
          <div class="q-avatar">P</div>
          <div>
            <div class="q-patient-label"><span class="q-badge"><i class="fa fa-user-injured" style="font-size:9px"></i> Patient asking question</span></div>
            <div class="q-name">Priya M.</div>
          </div>
          <div class="q-time">2 days ago</div>
        </div>
        <div class="q-text">
          Does this sunscreen work well under makeup? I use a liquid foundation and I'm worried about pilling.
        </div>
      </div>

      <!-- Prepopulated question 2 -->
      <div class="question-card">
        <div class="question-header">
          <div class="q-avatar">R</div>
          <div>
            <div class="q-patient-label"><span class="q-badge"><i class="fa fa-user-injured" style="font-size:9px"></i> Patient asking question</span></div>
            <div class="q-name">Rahul S.</div>
          </div>
          <div class="q-time">5 days ago</div>
        </div>
        <div class="q-text">
          Is this suitable for sensitive skin? I have rosacea and most sunscreens cause redness for me.
        </div>
      </div>

    </div><!-- /#qaList -->

    <div class="empty-qa" id="qaEmpty" style="display:none">
      <i class="fa fa-comments"></i>
      No questions yet. Be the first to ask!
    </div>

  </div><!-- /.qa-section -->

</div><!-- /.container -->


<!-- ════════════════════════════════
     RATE US MODAL
════════════════════════════════ -->
<div class="modal fade" id="rateModal" tabindex="-1" aria-labelledby="rateModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title" id="rateModalLabel" style="font-family:'DM Serif Display',serif;font-size:20px">
          Write a Review
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body pt-2">

        <!-- Star picker -->
        <label style="font-size:13px;font-weight:600;margin-bottom:8px;display:block">Your Rating</label>
        <div class="star-picker mb-3" id="starPicker">
          <span data-v="1" onclick="pickStar(1)">★</span>
          <span data-v="2" onclick="pickStar(2)">★</span>
          <span data-v="3" onclick="pickStar(3)">★</span>
          <span data-v="4" onclick="pickStar(4)">★</span>
          <span data-v="5" onclick="pickStar(5)">★</span>
        </div>

        <div class="mb-3">
          <label class="form-label" style="font-size:13px;font-weight:600">Name</label>
          <input type="text" class="form-control" id="rName" placeholder="Your name" />
        </div>
        <div class="mb-3">
          <label class="form-label" style="font-size:13px;font-weight:600">Skin Type</label>
          <select class="form-select" id="rSkin" style="font-family:'DM Sans',sans-serif;font-size:13px">
            <option value="">Select skin type</option>
            <option>Normal</option>
            <option>Oily</option>
            <option>Dry</option>
            <option>Combination</option>
            <option>Sensitive</option>
          </select>
        </div>
        <div class="mb-3">
          <label class="form-label" style="font-size:13px;font-weight:600">Review Title</label>
          <input type="text" class="form-control" id="rTitle" placeholder="Sum up your experience" />
        </div>
        <div class="mb-3">
          <label class="form-label" style="font-size:13px;font-weight:600">Your Review</label>
          <textarea class="form-control" id="rBody" rows="4" placeholder="Tell others what you think…" style="font-family:'DM Sans',sans-serif;font-size:13px;resize:none"></textarea>
        </div>
        <div id="rError" style="color:var(--red);font-size:12px;margin-bottom:10px;display:none">
          Please fill in all fields and select a star rating.
        </div>
      </div>
      <div class="modal-footer border-0 pt-0">
        <button type="button" class="btn-cancel-q" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn-submit-rate" onclick="submitReview()">Post Review</button>
      </div>
    </div>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script>
  // ── Star picker ──
  let pickedStars = 0;

  function pickStar(n) {
    pickedStars = n;
    document.querySelectorAll('#starPicker span').forEach((s, i) => {
      s.classList.toggle('lit', i < n);
    });
  }

  // ── Submit Review ──
  function submitReview() {
    const name = document.getElementById('rName').value.trim();
    const skin = document.getElementById('rSkin').value;
    const title = document.getElementById('rTitle').value.trim();
    const body = document.getElementById('rBody').value.trim();
    const err = document.getElementById('rError');

    if (!name || !title || !body || pickedStars === 0) {
      err.style.display = 'block';
      return;
    }
    err.style.display = 'none';

    const starStr = '★'.repeat(pickedStars) + (pickedStars < 5 ? '<span style="color:#ddd">' + '★'.repeat(5 - pickedStars) + '</span>' : '');
    const skinLine = skin ? `<span>Skin Type: ${skin}</span>` : '';

    const card = document.createElement('div');
    card.className = 'review-card';
    card.dataset.helpful = '0';
    card.dataset.rating = pickedStars;
    card.dataset.date = new Date().toISOString().slice(0, 10);
    card.innerHTML = `
      <div class="row g-0">
        <div class="col-12 col-sm-3 col-md-2 mb-3 mb-sm-0">
          <div class="reviewer-name">${escHtml(name)}</div>
          <div class="reviewer-meta">${skinLine}</div>
        </div>
        <div class="col-12 col-sm-9 col-md-10 ps-sm-3">
          <div class="review-stars">${starStr}</div>
          <div class="review-title">${escHtml(title)}</div>
          <div class="review-body">${escHtml(body)}</div>
          <div class="vote-row">
            <button class="vote-btn" onclick="likeReview(this)">
              <i class="fa fa-thumbs-up"></i> <span class="vote-num">0</span>
            </button>
            <button class="vote-btn dislike-btn">
              <i class="fa fa-thumbs-down"></i> <span class="vote-num">0</span>
            </button>
          </div>
        </div>
      </div>`;

    document.getElementById('reviewList').prepend(card);

    // reset
    ['rName', 'rTitle', 'rBody'].forEach(id => document.getElementById(id).value = '');
    document.getElementById('rSkin').value = '';
    pickStar(0);
    bootstrap.Modal.getInstance(document.getElementById('rateModal')).hide();
  }

  // ── Like/Dislike ──
  function likeReview(btn) {
    if (btn.classList.contains('liked')) {
      btn.classList.remove('liked');
      const n = btn.querySelector('.vote-num');
      n.textContent = Math.max(0, parseInt(n.textContent) - 1);
    } else {
      btn.classList.add('liked');
      const n = btn.querySelector('.vote-num');
      n.textContent = parseInt(n.textContent) + 1;
    }
  }

  // ── Sort reviews ──
  function sortReviews() {
    const val = document.getElementById('sortSelect').value;
    const list = document.getElementById('reviewList');
    const cards = Array.from(list.querySelectorAll('.review-card'));

    cards.sort((a, b) => {
      if (val === 'helpful') return parseInt(b.dataset.helpful) - parseInt(a.dataset.helpful);
      if (val === 'recent') return b.dataset.date.localeCompare(a.dataset.date);
      if (val === 'high') return parseInt(b.dataset.rating) - parseInt(a.dataset.rating);
      if (val === 'low') return parseInt(a.dataset.rating) - parseInt(b.dataset.rating);
    });

    cards.forEach(c => {
      c.style.animation = 'none';
      list.appendChild(c);
    });
    requestAnimationFrame(() => {
      cards.forEach(c => {
        c.style.animation = '';
        c.style.animationName = 'fadeSlideIn';
      });
    });
  }

  // ── Ask Question ──
  function openAskForm() {
    const f = document.getElementById('askFormWrap');
    f.style.display = 'block';
    f.scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
  }

  function closeAskForm() {
    document.getElementById('askFormWrap').style.display = 'none';
    document.getElementById('qError').style.display = 'none';
    document.getElementById('qName').value = '';
    document.getElementById('qText').value = '';
  }
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('openAskForm').addEventListener('click', openAskForm);
    document.getElementById('openAskForm2').addEventListener('click', openAskForm);
  });

  function submitQuestion() {
    const name = document.getElementById('qName').value.trim();
    const text = document.getElementById('qText').value.trim();
    const err = document.getElementById('qError');

    if (!name || !text) {
      err.style.display = 'block';
      return;
    }
    err.style.display = 'none';

    const initials = name.split(' ').map(w => w[0].toUpperCase()).join('').slice(0, 2);

    const now = new Date();
    const timeLabel = 'Just now';

    const card = document.createElement('div');
    card.className = 'question-card';
    card.innerHTML = `
      <div class="question-header">
        <div class="q-avatar">${initials}</div>
        <div>
          <div class="q-patient-label">
            <span class="q-badge"><i class="fa fa-user-injured" style="font-size:9px"></i> Patient asking question</span>
          </div>
          <div class="q-name">${escHtml(name)}</div>
        </div>
        <div class="q-time">${timeLabel}</div>
      </div>
      <div class="q-text">${escHtml(text)}</div>`;

    const qaList = document.getElementById('qaList');
    qaList.prepend(card);

    closeAskForm();
    card.scrollIntoView({
      behavior: 'smooth',
      block: 'center'
    });
  }

  // ── Escape HTML ──
  function escHtml(str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  // Tab switching
  function switchTab(el, id) {
    document.querySelectorAll('.info-tab').forEach(t => t.classList.remove('active'));
    el.classList.add('active');
    ['desc', 'how', 'other'].forEach(tid => {
      document.getElementById('tab-' + tid).style.display = tid === id ? '' : 'none';
    });
  }

  // Image gallery arrow controls
  let arrowControls = false;
  document.addEventListener('DOMContentLoaded', function() {
    if (!arrowControls) {
      const leftArrow = document.getElementById('arrowLeft');
      const rightArrow = document.getElementById('arrowRight');
      if (leftArrow) leftArrow.addEventListener('click', () => navigateGallery(-1));
      if (rightArrow) rightArrow.addEventListener('click', () => navigateGallery(1));
      arrowControls = true;
    }
  });

  function navigateGallery(direction) {
    const thumbs = document.querySelectorAll('#thumbCol img');
    if (thumbs.length === 0) return;
    
    let currentIdx = 0;
    thumbs.forEach((t, i) => {
      if (t.classList.contains('active')) currentIdx = i;
    });
    
    const newIdx = (currentIdx + direction + thumbs.length) % thumbs.length;
    thumbs[newIdx].click();
  }

  // ──── LOAD PRODUCT DATA ────
  async function loadProductData() {
    const productKey = getProductKeyFromFilename();
    
    try {
      const response = await fetch(new URL(`fetch_product_detail.php?product=${encodeURIComponent(productKey)}`, window.location.href).href);
      const result = await response.json();
      
      if (result.error || !result.product) {
        console.warn('Product data not found');
        return;
      }
      
      const product = result.product;
      displayProductData(product);
      loadRelatedProducts(product.category || 'skincare');
    } catch (error) {
      console.error('Error loading product data:', error);
    }
  }

  function getProductKeyFromFilename() {
    // First, check if there's a ?product= parameter in the URL
    const urlParams = new URLSearchParams(window.location.search);
    const productParam = urlParams.get('product');
    
    if (productParam) {
      return productParam;
    }
    
    // Fallback to extracting from filename
    const filename = window.location.pathname.split('/').pop().replace('.php', '');
    return filename;
  }

  function displayProductData(product) {
    // Update title and breadcrumb
    document.getElementById('productTitle').textContent = product.name || 'Product';
    document.getElementById('breadcrumbProduct').textContent = product.name || 'Product';
    document.getElementById('productSubtitle').textContent = '/' + (product.subtitle || product.concern || 'Skincare') + '/';
    
    // Update rating
    document.getElementById('productStars').textContent = product.stars || '★★★★★';
    document.getElementById('productReviews').textContent = (product.stars || '★★★★★') + ' | ' + (product.reviewsCount || '120') + ' reviews';
    
    // Update price and other info
    document.getElementById('productPrice').textContent = product.price || '₹0';
    document.getElementById('productDesc').textContent = product.subtitle || product.description || '';
    document.getElementById('productDescText').textContent = product.whatIs || product.description || '';
    document.getElementById('howToUseText').textContent = product.howToUse || 'Use as directed on the product label.';
    
    // Update images in gallery
    if (product.images && product.images.length > 0) {
      const thumbCol = document.getElementById('thumbCol');
      thumbCol.innerHTML = '';
      
      product.images.forEach((img, i) => {
        const thumb = document.createElement('img');
        thumb.src = img;
        thumb.className = 'thumb-item' + (i === 0 ? ' active' : '');
        thumb.alt = 'Product image ' + (i + 1);
        thumb.style.cursor = 'pointer';
        thumb.style.width = '60px';
        thumb.style.height = '60px';
        thumb.style.objectFit = 'cover';
        thumb.addEventListener('click', () => {
          document.getElementById('mainImg').src = img;
          document.querySelectorAll('#thumbCol img').forEach(t => t.classList.remove('active'));
          thumb.classList.add('active');
        });
        thumbCol.appendChild(thumb);
      });
      
      // Set main image
      if (product.images[0]) {
        const mainImg = document.getElementById('mainImg');
        mainImg.src = product.images[0];
        mainImg.style.width = '100%';
        mainImg.style.height = 'auto';
      }
    }
  }

  async function loadRelatedProducts(categoryName) {
    try {
      const response = await fetch(new URL(`fetch_category_products.php?category=${encodeURIComponent(categoryName)}`, window.location.href).href);
      const result = await response.json();
      
      if (result.error || !result.products) {
        console.warn('No related products found');
        return;
      }
      
      displayRelatedProducts(result.products.slice(0, 6));
    } catch (error) {
      console.error('Error loading related products:', error);
    }
  }

  function displayRelatedProducts(products) {
    const relatedHtml = products.map(p => `
      <div class="col-6 col-md-4 col-lg-3 mb-4">
        <div class="product-card" style="border: 1px solid #eee; border-radius: 8px; padding: 12px; text-align: center;">
          <a href="product-detail.php?product=${encodeURIComponent(p.id || p.sku || p.urlKey)}" style="text-decoration: none; color: inherit;">
            <img src="${p.imageUrl || (p.images && p.images.length > 0 ? p.images[0] : './assets/img/product.webp')}" alt="${p.name}" style="width: 100%; height: 180px; object-fit: cover; border-radius: 6px; margin-bottom: 10px;">
            <div style="font-weight: 600; font-size: 13px; color: #333; margin-bottom: 6px;">${p.name}</div>
            <div style="color: #999; font-size: 11px; margin-bottom: 8px;">${p.type || 'Product'}</div>
            <div style="color: #1a73e8; font-weight: 600; font-size: 14px;">${p.price || '₹0'}</div>
          </a>
        </div>
      </div>
    `).join('');
    
    const relatedSection = document.getElementById('relatedProductsSection');
    if (relatedSection) {
      relatedSection.innerHTML = `
        <h3 class="mb-4" style="font-size: 20px; font-weight: 700;">Related Products</h3>
        <div class="row">
          ${relatedHtml}
        </div>
      `;
    }
  }

  // Load on page ready
  document.addEventListener('DOMContentLoaded', loadProductData);
</script>
<!-- RELATED PRODUCTS SECTION (will be populated by JS) -->
<div id="relatedProductsSection"></div>

<?php include 'footer.php'; ?>
</body>

</html>